server:
  port: 8113
  tomcat:
      max-threads: 2000
      accept-count: 200
      max-connections: 2000
      max-http-post-size: -1
spring:
  application:
    name: 1013-saaf-app-deployee-server
  http:
  #文件上传配置
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
endpoints:
  shutdown:
    enabled: true
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: 139.159.227.77
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    port: 8760

#阿里oss 配置
oss:
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAIR3y4zOJRynX7
  accessKeySecret: jhxrupOChDUWc6kVvSWff9Y1Z0oDhp
  bucketName: saaf
  accessProtocol: http://

#fastdfs配置
fastdfs:
  connect_timeout_in_seconds: 2
  network_timeout_in_seconds: 30
  charset: utf-8
  http_anti_steal_token: false
  http_secret_key: FastDFS1234567890
  http_tracker_http_port: 80
  tracker_servers: #TrackerList参数,支持多个
    - 139.159.229.31:22122
    - 139.159.229.33:22122
  thumb_image: #缩略图生成参数
    width: 150
    height: 150
  access: #访问地址
   address: 139.159.229.31
   http_type: http://
   http_port: 80

