-- drop sequence rule: seq_tableName, limit 30 char length
drop sequence seq_act_bpm_category;
drop sequence seq_act_bpm_communicate;
drop sequence seq_act_bpm_config;
drop sequence seq_act_bpm_exception;
drop sequence seq_act_bpm_list;
drop sequence seq_act_bpm_notify_task;
drop sequence seq_act_bpm_permission;
drop sequence seq_act_bpm_role;
drop sequence seq_act_bpm_task_config;
drop sequence seq_act_bpm_task_delegate;
drop sequence seq_act_bpm_task_delegate_conf;
drop sequence seq_act_bpm_task_leavel;
drop sequence seq_act_bpm_task_processer;
drop sequence seq_act_bpm_task_urge_config;
drop sequence seq_act_evt_log;
drop sequence seq_act_ge_bytearray;
drop sequence seq_act_ge_property;
drop sequence seq_act_hi_actinst;
drop sequence seq_act_hi_attachment;
drop sequence seq_act_hi_comment;
drop sequence seq_act_hi_detail;
drop sequence seq_act_hi_identitylink;
drop sequence seq_act_hi_procinst;
drop sequence seq_act_hi_taskinst;
drop sequence seq_act_hi_varinst;
drop sequence seq_act_id_group;
drop sequence seq_act_id_info;
drop sequence seq_act_id_membership;
drop sequence seq_act_id_user;
drop sequence seq_act_procdef_info;
drop sequence seq_act_re_deployment;
drop sequence seq_act_re_model;
drop sequence seq_act_re_procdef;
drop sequence seq_act_ru_event_subscr;
drop sequence seq_act_ru_execution;
drop sequence seq_act_ru_identitylink;
drop sequence seq_act_ru_job;
drop sequence seq_act_ru_task;
drop sequence seq_act_ru_variable;
drop sequence seq_admin_area_info;
drop sequence seq_base_access_basedata;
drop sequence seq_base_adminstrative_region;
drop sequence seq_base_api_center_h;
drop sequence seq_base_api_center_l;
drop sequence seq_base_api_management;
drop sequence seq_base_app_auth_contain;
drop sequence seq_base_app_auth_exclude;
drop sequence seq_base_app_deployee_info;
drop sequence seq_base_app_deployee_menu;
drop sequence seq_base_attachment;
drop sequence seq_base_button_data;
drop sequence seq_base_button_data_language;
drop sequence seq_base_channel;
drop sequence seq_base_channel_privilege;
drop sequence seq_base_cms_article;
drop sequence seq_base_cms_carousel;
drop sequence seq_base_cms_carousel_city;
drop sequence seq_base_cms_category;
drop sequence seq_base_cms_web_notice;
drop sequence seq_base_cms_web_notice_city;
drop sequence seq_base_common_message_confir;
drop sequence seq_base_common_transaction_co;
drop sequence seq_base_common_txn_confirm;
drop sequence seq_base_cust_pda_user_relatio;
drop sequence seq_base_data_export;
drop sequence seq_base_department;
drop sequence seq_base_department_cust;
drop sequence seq_base_department_hierarchy;
drop sequence seq_base_department_lan;
drop sequence seq_base_deployee_app_host_inf;
drop sequence seq_base_deployee_app_info;
drop sequence seq_base_deployee_app_menu;
drop sequence seq_base_export_record;
drop sequence seq_base_faq_help;
drop sequence seq_base_function_collection;
drop sequence seq_base_function_collection_l;
drop sequence seq_base_function_collection_u;
drop sequence seq_base_inv_store_contact_t;
drop sequence seq_base_inv_store_t;
drop sequence seq_base_job;
drop sequence seq_base_job_lan;
drop sequence seq_base_login_log;
drop sequence seq_base_lookup_types;
drop sequence seq_base_lookup_types_lan;
drop sequence seq_base_lookup_values;
drop sequence seq_base_lookup_values_lan;
drop sequence seq_base_manual_supplement;
drop sequence seq_base_menu;
drop sequence seq_base_menu_language;
drop sequence seq_base_message_bu;
drop sequence seq_base_message_content;
drop sequence seq_base_message_department;
drop sequence seq_base_message_instation;
drop sequence seq_base_message_person;
drop sequence seq_base_org_responsibility;
drop sequence seq_base_organization;
drop sequence seq_base_organization_lan;
drop sequence seq_base_pda_inv_cfg;
drop sequence seq_base_pda_role_cfg;
drop sequence seq_base_person;
drop sequence seq_base_person_assign;
drop sequence seq_base_person_cust;
drop sequence seq_base_person_lan;
drop sequence seq_base_person_level;
drop sequence seq_base_person_organization;
drop sequence seq_base_position;
drop sequence seq_base_position_lan;
drop sequence seq_base_privilege_detail;
drop sequence seq_base_privilege_record;
drop sequence seq_base_product_info;
drop sequence seq_base_product_inv;
drop sequence seq_base_profile;
drop sequence seq_base_profile_value;
drop sequence seq_base_publish_app_info;
drop sequence seq_base_report_charts_type;
drop sequence seq_base_report_charts_type_la;
drop sequence seq_base_report_datasource;
drop sequence seq_base_report_datasource_lan;
drop sequence seq_base_report_group;
drop sequence seq_base_report_group_header;
drop sequence seq_base_report_header;
drop sequence seq_base_report_line;
drop sequence seq_base_request_log;
drop sequence seq_base_resource;
drop sequence seq_base_resource_lan;
drop sequence seq_base_responsibility;
drop sequence seq_base_responsibility_lan;
drop sequence seq_base_responsibility_role;
drop sequence seq_base_responsibility_role_l;
drop sequence seq_base_role;
drop sequence seq_base_role_language;
drop sequence seq_base_role_menu;
drop sequence seq_base_role_resource;
drop sequence seq_base_system_sso;
drop sequence seq_base_task_collection;
drop sequence seq_base_user_responsibility;
drop sequence seq_base_users;
drop sequence seq_base_users_language;
drop sequence seq_base_warehouse_mapping;
drop sequence seq_base_wechat_mng;
drop sequence seq_cux_cdm_access_basedata;
drop sequence seq_demo;
drop sequence seq_domain_wx;
drop sequence seq_ew_configuration_head;
drop sequence seq_ew_configuration_line;
drop sequence seq_ew_configuration_man;
drop sequence seq_ew_handle;
drop sequence seq_msg_cfg;
drop sequence seq_msg_history;
drop sequence seq_msg_instance;
drop sequence seq_msg_log;
drop sequence seq_msg_receive_sql;
drop sequence seq_msg_source_cfg;
drop sequence seq_msg_td;
drop sequence seq_msg_temple_cfg;
drop sequence seq_msg_user;
drop sequence seq_page_model_group_detail;
drop sequence seq_page_model_group_info;
drop sequence seq_page_model_info;
drop sequence seq_per_all_assignments_f;
drop sequence seq_per_all_people_f;
drop sequence seq_pub_users_organization;
drop sequence seq_qrtz_blob_triggers;
drop sequence seq_qrtz_calendars;
drop sequence seq_qrtz_cron_triggers;
drop sequence seq_qrtz_fired_triggers;
drop sequence seq_qrtz_job_details;
drop sequence seq_qrtz_locks;
drop sequence seq_qrtz_paused_trigger_grps;
drop sequence seq_qrtz_scheduler_state;
drop sequence seq_qrtz_simple_triggers;
drop sequence seq_qrtz_simprop_triggers;
drop sequence seq_qrtz_triggers;
drop sequence seq_rule_business_line;
drop sequence seq_rule_dim;
drop sequence seq_rule_expression;
drop sequence seq_rule_expressiondim;
drop sequence seq_rule_mapping_business;
drop sequence seq_saaf_file_upload;
drop sequence seq_saaf_webservice_info;
drop sequence seq_saaf_webservice_param_info;
drop sequence seq_schedule_job_access_orgs;
drop sequence seq_schedule_job_parameters;
drop sequence seq_schedule_job_resp;
drop sequence seq_schedule_jobs;
drop sequence seq_schedule_log;
drop sequence seq_schedule_schedules;
drop sequence seq_schedule_schedules_error;
drop sequence seq_user_pwd_temp;
drop sequence seq_wx_user;
drop sequence seq_z_test;
drop sequence seq_base_profile_value_lan;
drop sequence seq_base_issue_feedback;
drop sequence seq_base_profile_lan;


-- create sequence rule: seq_tableName ,limit 30 char length
create sequence seq_act_bpm_category start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_communicate start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_config start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_exception start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_list start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_notify_task start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_permission start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_role start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_task_config start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_task_delegate start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_task_delegate_conf start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_task_leavel start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_task_processer start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_bpm_task_urge_config start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_evt_log start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_ge_bytearray start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_ge_property start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_hi_actinst start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_hi_attachment start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_hi_comment start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_hi_detail start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_hi_identitylink start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_hi_procinst start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_hi_taskinst start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_hi_varinst start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_id_group start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_id_info start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_id_membership start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_id_user start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_procdef_info start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_re_deployment start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_re_model start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_re_procdef start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_ru_event_subscr start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_ru_execution start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_ru_identitylink start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_ru_job start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_ru_task start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_act_ru_variable start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_admin_area_info start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_access_basedata start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_adminstrative_region start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_api_center_h start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_api_center_l start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_api_management start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_app_auth_contain start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_app_auth_exclude start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_app_deployee_info start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_app_deployee_menu start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_attachment start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_button_data start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_button_data_language start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_channel start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_channel_privilege start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_cms_article start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_cms_carousel start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_cms_carousel_city start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_cms_category start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_cms_web_notice start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_cms_web_notice_city start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_common_message_confir start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_common_transaction_co start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_common_txn_confirm start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_cust_pda_user_relatio start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_data_export start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_department start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_department_cust start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_department_hierarchy start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_department_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_deployee_app_host_inf start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_deployee_app_info start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_deployee_app_menu start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_export_record start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_faq_help start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_function_collection start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_function_collection_l start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_function_collection_u start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_inv_store_contact_t start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_inv_store_t start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_job start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_job_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_login_log start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_lookup_types start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_lookup_types_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_lookup_values start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_lookup_values_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_manual_supplement start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_menu start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_menu_language start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_message_bu start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_message_content start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_message_department start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_message_instation start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_message_person start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_org_responsibility start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_organization start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_organization_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_pda_inv_cfg start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_pda_role_cfg start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_person start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_person_assign start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_person_cust start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_person_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_person_level start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_person_organization start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_position start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_position_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_privilege_detail start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_privilege_record start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_product_info start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_product_inv start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_profile start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_profile_value start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_publish_app_info start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_report_charts_type start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_report_charts_type_la start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_report_datasource start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_report_datasource_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_report_group start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_report_group_header start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_report_header start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_report_line start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_request_log start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_resource start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_resource_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_responsibility start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_responsibility_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_responsibility_role start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_responsibility_role_l start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_role start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_role_language start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_role_menu start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_role_resource start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_system_sso start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_task_collection start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_user_responsibility start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_users start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_users_language start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_warehouse_mapping start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_wechat_mng start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_cux_cdm_access_basedata start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_demo start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_domain_wx start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_ew_configuration_head start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_ew_configuration_line start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_ew_configuration_man start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_ew_handle start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_msg_cfg start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_msg_history start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_msg_instance start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_msg_log start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_msg_receive_sql start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_msg_source_cfg start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_msg_td start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_msg_temple_cfg start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_msg_user start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_page_model_group_detail start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_page_model_group_info start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_page_model_info start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_per_all_assignments_f start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_per_all_people_f start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_pub_users_organization start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_qrtz_blob_triggers start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_qrtz_calendars start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_qrtz_cron_triggers start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_qrtz_fired_triggers start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_qrtz_job_details start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_qrtz_locks start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_qrtz_paused_trigger_grps start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_qrtz_scheduler_state start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_qrtz_simple_triggers start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_qrtz_simprop_triggers start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_qrtz_triggers start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_rule_business_line start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_rule_dim start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_rule_expression start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_rule_expressiondim start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_rule_mapping_business start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_saaf_file_upload start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_saaf_webservice_info start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_saaf_webservice_param_info start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_schedule_job_access_orgs start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_schedule_job_parameters start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_schedule_job_resp start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_schedule_jobs start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_schedule_log start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_schedule_schedules start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_schedule_schedules_error start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_user_pwd_temp start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_wx_user start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_z_test start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_profile_value_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_issue_feedback start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
create sequence seq_base_profile_lan start with 1 increment by 1 nomaxvalue nominvalue nocycle nocache;
