create sequence SEQ_TTA_FREE_GOODS  

increment by 1  

start with 1  

maxvalue 9999999  

cycle  

nocache;  

CREATE TABLE "TTA_FREE_GOODS" (
"ID" NUMBER  NOT NULL,
"GROUP_DESC" VARCHAR2(100),
"BRAND" VARCHAR2(100),
"TERMS" VARCHAR2(100),
"COLLECTTYPE" VARCHAR2(50),
"SUMTYPE" VARCHAR2(50),
"AMOUNT" VARCHAR2(50),
"PER" VARCHAR2(50),
"SALSEPER" VARCHAR2(50),
"FEEINTAS" VARCHAR2(50),
"FEENOTAX" VARCHAR2(50),
"PURCHASE" VARCHAR2(50),
"STANDARDCHARGED" VARCHAR2(50),
"ACTUALCHARGE" VARCHAR2(50),
"VARIENCE" VARCHAR2(50),
"CHECKINGREMARK" VARCHAR2(500),
"ACTUALRECEIVEDAMOUNT" VARCHAR2(50),
"PURCHASEACTION" VARCHAR2(50),
"REMARK" VARCHAR2(500),

TIMES_VERSION VARCHAR2(50),
STATUS VARCHAR2(50),

"CREATION_DATE" DATE DEFAULT SYSDATE, 
"CREATED_BY" NUMBER(*,0), 
"LAST_UPDATED_BY" NUMBER(*,0), 
"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
"LAST_UPDATE_LOGIN" NUMBER(*,0)
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "TTA_FREE_GOODS" IS ' 免费商品';
COMMENT ON COLUMN "TTA_FREE_GOODS"."ID" IS 'ID';
COMMENT ON COLUMN "TTA_FREE_GOODS"."GROUP_DESC" IS '部门';
COMMENT ON COLUMN "TTA_FREE_GOODS"."BRAND" IS '品牌';
COMMENT ON COLUMN "TTA_FREE_GOODS"."TERMS" IS '条款';
COMMENT ON COLUMN "TTA_FREE_GOODS"."COLLECTTYPE" IS '收款方式';
COMMENT ON COLUMN "TTA_FREE_GOODS"."SUMTYPE" IS '采购额核算方式';
COMMENT ON COLUMN "TTA_FREE_GOODS"."AMOUNT" IS '金额';
COMMENT ON COLUMN "TTA_FREE_GOODS"."PER" IS '%';
COMMENT ON COLUMN "TTA_FREE_GOODS"."SALSEPER" IS 'Sales part%';
COMMENT ON COLUMN "TTA_FREE_GOODS"."FEEINTAS" IS '201812 YTD actual Purchase （折扣前净采购额含税)';
COMMENT ON COLUMN "TTA_FREE_GOODS"."FEENOTAX" IS '201812 YTD actual Purchase （折扣后净采购额含税)';
COMMENT ON COLUMN "TTA_FREE_GOODS"."PURCHASE" IS 'FCST 2018 FY Purchase （with tax)';
COMMENT ON COLUMN "TTA_FREE_GOODS"."STANDARDCHARGED" IS '2018 FY Standard charged based on rate card';
COMMENT ON COLUMN "TTA_FREE_GOODS"."ACTUALCHARGE" IS '2018 FY Actual charge to CA/ABOI/货款调整 Amount';
COMMENT ON COLUMN "TTA_FREE_GOODS"."VARIENCE" IS 'Varience(only negative items are counted)';
COMMENT ON COLUMN "TTA_FREE_GOODS"."CHECKINGREMARK" IS 'BIC Checking Remark';
COMMENT ON COLUMN "TTA_FREE_GOODS"."ACTUALRECEIVEDAMOUNT" IS ' 2018YTD~2019W07 PO Actual Received Amount';
COMMENT ON COLUMN "TTA_FREE_GOODS"."PURCHASEACTION" IS '采购行动';
COMMENT ON COLUMN "TTA_FREE_GOODS"."REMARK" IS '备注（如已收取请提供相关的订单号，如折扣收取/确认不收取请备注原因）';

COMMENT ON COLUMN TTA_IR_TERMS.TIMES_VERSION IS '年月日（记录操作版本）';
COMMENT ON COLUMN TTA_IR_TERMS.STATUS IS '状态(提交时锁定)';

ALTER TABLE "TTA_FREE_GOODS" ADD PRIMARY KEY ("ID");
