create sequence SEQ_TTA_IR_TERMS  

increment by 1  

start with 1  

maxvalue 9999999  

cycle  

nocache;  



CREATE TABLE TTA_IR_TERMS (
ID NUMBER  NOT NULL,
DEPARTMENT VARCHAR2(250),
BRAND VARCHAR2(250),
ONE VARCHAR2(50),
TWO VARCHAR2(50),
THREE VARCHAR2(50),
FOUR VARCHAR2(50),
FIVE VARCHAR2(50),
SIX VARCHAR2(50),
SEVEN VARCHAR2(50),
EIGHT VARCHAR2(50),

ONE_PER VARCHAR2(50),
TWO_PER VARCHAR2(50),
THREE_PER VARCHAR2(50),
FOUR_PER VARCHAR2(50),
FIVE_PER VARCHAR2(50),
SIX_PER VARCHAR2(50),
SEVEN_PER VARCHAR2(50),
EIGHT_PER VARCHAR2(50),


PURCHASE VARCHAR2(50),
FY_PURCHASE VARCHAR2(50),
IR_PER VARCHAR2(50),
FIRST_TIER VARCHAR2(50),
LAST_TIER VARCHAR2(50),
FORECASTED_IR_PER VARCHAR2(50),
NEXT_IR_PER VARCHAR2(50),
POTENTIAL_FORWARD_BUY VARCHAR2(50),
AFTER_POTENTIAL VARCHAR2(50),
EXTRAL_IR VARCHAR2(50),
RETURN_RATE VARCHAR2(50),
BIC_REMARK VARCHAR2(1000),
FOLLOW_UP_ACTION VARCHAR2(50),
EXTRA_PO_PLANNING VARCHAR2(50),
REMARK VARCHAR2(1000),

TIMES_VERSION VARCHAR2(50),
STATUS VARCHAR2(50),

CREATION_DATE DATE DEFAULT SYSDATE, 
CREATED_BY NUMBER(*,0), 
LAST_UPDATED_BY NUMBER(*,0), 
LAST_UPDATE_DATE DATE DEFAULT SYSDATE, 
LAST_UPDATE_LOGIN NUMBER(*,0)
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE TTA_IR_TERMS IS ' IR Term Report';
COMMENT ON COLUMN TTA_IR_TERMS.DEPARTMENT IS '部门';
COMMENT ON COLUMN TTA_IR_TERMS.BRAND IS '品牌';
COMMENT ON COLUMN TTA_IR_TERMS.ONE IS '第一层';
COMMENT ON COLUMN TTA_IR_TERMS.TWO IS '第二层';
COMMENT ON COLUMN TTA_IR_TERMS.THREE IS '第三层';
COMMENT ON COLUMN TTA_IR_TERMS.FOUR IS '第四层';
COMMENT ON COLUMN TTA_IR_TERMS.FIVE IS '第五层';
COMMENT ON COLUMN TTA_IR_TERMS.SIX IS '第六层';
COMMENT ON COLUMN TTA_IR_TERMS.SEVEN IS '第七层';
COMMENT ON COLUMN TTA_IR_TERMS.EIGHT IS '第八层';
COMMENT ON COLUMN TTA_IR_TERMS.ONE_PER IS '第一层%';
COMMENT ON COLUMN TTA_IR_TERMS.TWO_PER IS '第二层%';
COMMENT ON COLUMN TTA_IR_TERMS.THREE_PER IS '第三层%';
COMMENT ON COLUMN TTA_IR_TERMS.FOUR_PER IS '第四层%';
COMMENT ON COLUMN TTA_IR_TERMS.FIVE_PER IS '第五层%';
COMMENT ON COLUMN TTA_IR_TERMS.SIX_PER IS '第六层%';
COMMENT ON COLUMN TTA_IR_TERMS.SEVEN_PER IS '第七层%';
COMMENT ON COLUMN TTA_IR_TERMS.EIGHT_PER IS '第八层%';

COMMENT ON COLUMN TTA_IR_TERMS.PURCHASE IS '关联过去OI账单导入，取折扣前净采购额（折扣前），统计关联供应商总额';
COMMENT ON COLUMN TTA_IR_TERMS.FY_PURCHASE IS '（实际采购额（OI账单-净采购额（折扣前））/截止到上一月止的月份数）*12';
COMMENT ON COLUMN TTA_IR_TERMS.IR_PER IS '预计IR%';
COMMENT ON COLUMN TTA_IR_TERMS.FIRST_TIER IS '是否已达第一层';
COMMENT ON COLUMN TTA_IR_TERMS.LAST_TIER IS '是否已达最后一层';
COMMENT ON COLUMN TTA_IR_TERMS.FORECASTED_IR_PER IS '预计IR$';
COMMENT ON COLUMN TTA_IR_TERMS.NEXT_IR_PER IS '下一层目标的IR%';
COMMENT ON COLUMN TTA_IR_TERMS.POTENTIAL_FORWARD_BUY IS '为达到下一层目标需追加的采购额';
COMMENT ON COLUMN TTA_IR_TERMS.AFTER_POTENTIAL IS '追加后的IR$';
COMMENT ON COLUMN TTA_IR_TERMS.EXTRAL_IR IS 'IR 增加额';
COMMENT ON COLUMN TTA_IR_TERMS.RETURN_RATE IS '追加IR占追加采购金额比例(投资回报率)';
COMMENT ON COLUMN TTA_IR_TERMS.BIC_REMARK IS 'BIC_REMARK';
COMMENT ON COLUMN TTA_IR_TERMS.FOLLOW_UP_ACTION IS 'Follow up action';
COMMENT ON COLUMN TTA_IR_TERMS.EXTRA_PO_PLANNING IS 'extra PO planning';
COMMENT ON COLUMN TTA_IR_TERMS.TIMES_VERSION IS '年月日（记录操作版本）';
COMMENT ON COLUMN TTA_IR_TERMS.STATUS IS '状态(提交时锁定)';

ALTER TABLE TTA_IR_TERMS ADD PRIMARY KEY (ID);
