create sequence SEQ_TTA_OSD_MONTHLY_CHECKING 

increment by 1  

start with 1  

maxvalue 9999999  

cycle  

nocache;  


/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.1.0.7.0

Source Server         : xe
Source Server Version : 120100
Source Host           : 139.159.224.135:1521
Source Schema         : TTASYS

Target Server Type    : ORACLE
Target Server Version : 120100
File Encoding         : 65001

Date: 2019-07-26 09:05:35
*/


-- ----------------------------
-- Table structure for TTA_OSD_MONTHLY_CHECKING
-- ----------------------------
DROP TABLE TTA_OSD_MONTHLY_CHECKING;
CREATE TABLE TTA_OSD_MONTHLY_CHECKING (
ID NUMBER NOT NULL ,
PROMNUMBER VARCHAR2(50 BYTE) NULL ,
OSD VARCHAR2(50 BYTE) NULL ,
PROMOTION_GUIDELINE VARCHAR2(50 BYTE) NULL ,
STORE_NUM VARCHAR2(50 BYTE) NULL ,
DEPT_CODE VARCHAR2(50 BYTE) NULL ,
GROUP_DESC VARCHAR2(100 BYTE) NULL ,
DEPT_DESC VARCHAR2(100 BYTE) NULL ,
SALES_SITE2 VARCHAR2(100 BYTE) NULL ,
PRODUCT_CODE VARCHAR2(50 BYTE) NULL ,
CN_NAME VARCHAR2(100 BYTE) NULL ,
TRADE_REMARK VARCHAR2(255 BYTE) NULL ,
CONTENT VARCHAR2(500 BYTE) NULL ,
PRIOR_VENDOR_CODE VARCHAR2(80 BYTE) NULL ,
PRIOR_VENDOR_NAME VARCHAR2(250 BYTE) NULL ,
CONTRACT_OWNER_DEPT VARCHAR2(255 BYTE) NULL ,
CONTRACT_YEAR VARCHAR2(50 BYTE) NULL ,
CONTRACT_STATUS VARCHAR2(50 BYTE) NULL ,
CONTRACT_MASTER VARCHAR2(455 BYTE) NULL ,
AGREEMENT_STANDARDS VARCHAR2(255 BYTE) NULL ,
AGREEMENT_UNIT VARCHAR2(50 BYTE) NULL ,
DEPT_STANDARDS VARCHAR2(255 BYTE) NULL ,
DEPT_UNIT VARCHAR2(50 BYTE) NULL ,
CHARGE_STANDARDS VARCHAR2(50 BYTE) NULL ,
UNCONFIRM_VENDOR_CODE VARCHAR2(80 BYTE) NULL ,
UNCONFIRM_VENDOR_NAME VARCHAR2(255 BYTE) NULL ,
RECEIVE_AMOUNT VARCHAR2(50 BYTE) NULL ,
ORIGINAL_AMOUNT VARCHAR2(50 BYTE) NULL ,
UNCONFIRM_AMOUNT VARCHAR2(50 BYTE) NULL ,
DIFFERENCE VARCHAR2(50 BYTE) NULL ,
SPILT_VENODR VARCHAR2(50 BYTE) NULL ,
PURCHASE VARCHAR2(50 BYTE) NULL ,
COLLECT VARCHAR2(50 BYTE) NULL ,
EXEMPTION_REASON VARCHAR2(255 BYTE) NULL ,
EXEMPTION_REASON2 VARCHAR2(255 BYTE) NULL ,
DEBIT_ORDER_CODE VARCHAR2(50 BYTE) NULL ,
REMARK VARCHAR2(455 BYTE) NULL ,
CREATION_DATE DATE DEFAULT SYSDATE  NULL ,
CREATED_BY NUMBER NULL ,
LAST_UPDATED_BY NUMBER NULL ,
LAST_UPDATE_DATE DATE DEFAULT SYSDATE  NULL ,
LAST_UPDATE_LOGIN NUMBER NULL ,
SALES_SITE_ID NUMBER NULL ,
PROMOTION_GUIDELINE_ID NUMBER NULL ,
STATUS NUMBER NULL ,
PARENT_ID NUMBER NULL ,
TYPE VARCHAR2(50 BYTE) NULL ,
POG_ID NUMBER NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE TTA_OSD_MONTHLY_CHECKING IS  '促销位置基础数据维护';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.ID IS 'ID';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.PROMNUMBER IS '促销期间';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.OSD IS 'OSD';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.PROMOTION_GUIDELINE IS '促销陈列位置';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.STORE_NUM IS '生效区域店铺计数';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.DEPT_CODE IS 'category code';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.GROUP_DESC IS '部门';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.DEPT_DESC IS 'Category（品类）';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.SALES_SITE2 IS '促销位置-2';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.PRODUCT_CODE IS '产品编号';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.CN_NAME IS '中文名称';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.TRADE_REMARK IS '品牌';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.CONTENT IS '活动内容';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.PRIOR_VENDOR_CODE IS '优先供应商编号';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.PRIOR_VENDOR_NAME IS '优先供应商名称';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.CONTRACT_OWNER_DEPT IS 'Contract Owner Dept';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.CONTRACT_YEAR IS '合同年份';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.CONTRACT_STATUS IS '合作状态';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.CONTRACT_MASTER IS '合同条款';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.AGREEMENT_STANDARDS IS '协定标准';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.AGREEMENT_UNIT IS '单位';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.DEPT_STANDARDS IS '部门标准';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.DEPT_UNIT IS '单位';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.CHARGE_STANDARDS IS '计收标准';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.UNCONFIRM_VENDOR_CODE IS '需采购确认供应商编号';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.UNCONFIRM_VENDOR_NAME IS '需采购确认供应商名称';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.RECEIVE_AMOUNT IS '应收金额';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.ORIGINAL_AMOUNT IS '原应收金额';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.UNCONFIRM_AMOUNT IS '需采购确认收取金额';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.DIFFERENCE IS '差异';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.SPILT_VENODR IS '是否拆分供应商';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.PURCHASE IS '采购行动';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.COLLECT IS '收取方式';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.EXEMPTION_REASON IS '如采购行动选择确认不收取或者折扣收取需在下拉菜单选择豁免原因';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.EXEMPTION_REASON2 IS '如采购行动选择确认不收取或者折扣收取需在下拉菜单选择豁免原因（二级）';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.DEBIT_ORDER_CODE IS '借记单编号';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.REMARK IS '备注';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.LAST_UPDATE_LOGIN IS '促销位置ID';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.TYPE IS '字段隔离，区分不同报表数据';
COMMENT ON COLUMN TTA_OSD_MONTHLY_CHECKING.POG_ID IS 'tta_pog_space_line id';

-- ----------------------------
-- Indexes structure for table TTA_OSD_MONTHLY_CHECKING
-- ----------------------------

-- ----------------------------
-- Checks structure for table TTA_OSD_MONTHLY_CHECKING
-- ----------------------------
ALTER TABLE TTA_OSD_MONTHLY_CHECKING ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table TTA_OSD_MONTHLY_CHECKING
-- ----------------------------
ALTER TABLE TTA_OSD_MONTHLY_CHECKING ADD PRIMARY KEY (ID);



