create sequence SEQ_OSD_SALES_SITE  

increment by 1  

start with 1  

maxvalue 9999999  

cycle  

nocache;  

CREATE TABLE "TTA_OSD_SALES_SITE" (
"SALES_SITE_ID" NUMBER  NOT NULL,
"SALES_SITE" VARCHAR2(50),
"PROMOTION_GUIDELINE" VARCHAR2(50),
"WORKING" VARCHAR2(50),
"STATUS" VARCHAR2(50),
"CREATION_DATE" DATE DEFAULT SYSDATE, 
"CREATED_BY" NUMBER(*,0), 
"LAST_UPDATED_BY" NUMBER(*,0), 
"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
"LAST_UPDATE_LOGIN" NUMBER(*,0)
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "TTA_OSD_SALES_SITE" IS ' 促销位置基础数据维护';
COMMENT ON COLUMN "TTA_OSD_SALES_SITE"."SALES_SITE_ID" IS 'OSD_ID';
COMMENT ON COLUMN "TTA_OSD_SALES_SITE"."SALES_SITE" IS '促销位置';
COMMENT ON COLUMN "TTA_OSD_SALES_SITE"."PROMOTION_GUIDELINE" IS '促销陈列位置';
COMMENT ON COLUMN "TTA_OSD_SALES_SITE"."WORKING" IS 'WORKING';
COMMENT ON COLUMN "TTA_OSD_SALES_SITE"."STATUS" IS '失效标识';

ALTER TABLE "TTA_OSD_SALES_SITE" ADD PRIMARY KEY ("SALES_SITE_ID");
