create sequence SEQ_TTA_HWB_SITTING_PLAN

increment by 1  

start with 1  

maxvalue 99999999  

cycle  

nocache;  

CREATE TABLE TTA_HWB_SITTING_PLAN (
ID NUMBER  NOT NULL,
TABLE_NO VARCHAR2(30),
INDEX_NUM VARCHAR2(10),
DEPT VARCHAR2(100),
NAME_EN VARCHAR2(100),
NAME_CN VARCHAR2(100),
TITLE_EN VARCHAR2(250),
BRAND_ENORCN VARCHAR2(250),
TEND_CARD VARCHAR2(50),
CELL_PHONE_NUMBER VARCHAR2(50),
ATTEND VARCHAR2(50),
WTC VARCHAR2(50)

TIMES_VERSION VARCHAR2(50),
STATUS VARCHAR2(50),

CREATION_DATE DATE DEFAULT SYSDATE, 
CREATED_BY NUMBER(*,0), 
LAST_UPDATED_BY NUMBER(*,0), 
LAST_UPDATE_DATE DATE DEFAULT SYSDATE, 
LAST_UPDATE_LOGIN NUMBER(*,0)
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE TTA_HWB_SITTING_PLAN IS ' AWARD_POLIST';
COMMENT ON COLUMN TTA_HWB_SITTING_PLAN.ID IS 'ID';
COMMENT ON COLUMN TTA_HWB_SITTING_PLAN.ATTEND IS '下午发布会是否参加';
COMMENT ON COLUMN TTA_HWB_SITTING_PLAN.BRAND_ENORCN IS 'Brand (EN/CN)';


ALTER TABLE TTA_HWB_SITTING_PLAN ADD PRIMARY KEY (ID);
