create sequence SEQ_TTA_DEPT_DEFAULT_STANDARD  

increment by 1  

start with 1  

maxvalue 9999999  

cycle  

nocache;  

CREATE TABLE TTA_DEPT_DEFAULT_STANDARD (
ID NUMBER  NOT NULL,
PROPOSAL_CODE VARCHAR2(100),
STEP_DEPT VARCHAR2(100),
COST_TYPE VARCHAR2(100),
DEPT1 VARCHAR2(100),
DEPT2 VARCHAR2(100),
DEPT3 VARCHAR2(100),
ITEM_PROJECT VARCHAR2(150),
COMPANY_STANDARD VARCHAR2(100),
DEFAULT_STANDARD1 VARCHAR2(100),
DEFAULT_UNIT1 VARCHAR2(50),
DEFAULT_STANDARD2 VARCHAR2(100),
DEFAULT_UNIT2 VARCHAR2(50),
DEFAULT_STANDARD3 VARCHAR2(100),
DEFAULT_UNIT3 VARCHAR2(50),

STATUS VARCHAR2(50),

CREATION_DATE DATE DEFAULT SYSDATE, 
CREATED_BY NUMBER(*,0), 
LAST_UPDATED_BY NUMBER(*,0), 
LAST_UPDATE_DATE DATE DEFAULT SYSDATE, 
LAST_UPDATE_LOGIN NUMBER(*,0)
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE TTA_DEPT_DEFAULT_STANDARD IS ' 部门协定标准（其他协议）';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.ID IS 'ID';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.PROPOSAL_CODE IS 'proposal编号';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.STEP_DEPT IS '是否跨部门';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.COST_TYPE IS '费用类型';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.DEPT1 IS '部门1';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.DEPT2 IS '部门2';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.DEPT3 IS '部门3';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.ITEM_PROJECT IS 'item项目';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.COMPANY_STANDARD IS '公司标准';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.DEFAULT_STANDARD1 IS '协定标准1';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.DEFAULT_UNIT1 IS '收取单位1';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.DEFAULT_STANDARD2 IS '协定标准2';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.DEFAULT_UNIT2 IS '收取单位2';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.DEFAULT_STANDARD3 IS '协定标准3';
COMMENT ON COLUMN TTA_DEPT_DEFAULT_STANDARD.DEFAULT_UNIT3 IS '收取单位3';


ALTER TABLE TTA_DEPT_DEFAULT_STANDARD ADD PRIMARY KEY (ID);
