create sequence SEQ_TTA_HWB_ATTENDANCE_FEE

increment by 1  

start with 1  

maxvalue 99999999  

cycle  

nocache;  

CREATE TABLE TTA_HWB_ATTENDANCE_FEE (
ID NUMBER  NOT NULL,
DEPT VARCHAR2(30),
BRAND_ENORCN VARCHAR2(10),
NUM VARCHAR2(100),
FEE_TYPE VARCHAR2(100),
RATE_CARD VARCHAR2(100),
FEE_GROUP VARCHAR2(250),
CATEGORY VARCHAR2(250),
CONTENT VARCHAR2(50),
VENDOR_CODE VARCHAR2(50),
VENDOR_NAME VARCHAR2(50),
BRAND VARCHAR2(50),
AMOUNT VARCHAR2(50),
CONFIRM_AMOUNT VARCHAR2(50),
FG VARCHAR2(50),
DIFFERENT VARCHAR2(50),
ACTIVE VARCHAR2(50),
PROJECT_TYPE VARCHAR2(50),
REMARK VARCHAR2(50),

TIMES_VERSION VARCHAR2(50),
STATUS VARCHAR2(50),

CREATION_DATE DATE DEFAULT SYSDATE, 
CREATED_BY NUMBER(*,0), 
LAST_UPDATED_BY NUMBER(*,0), 
LAST_UPDATE_DATE DATE DEFAULT SYSDATE, 
LAST_UPDATE_LOGIN NUMBER(*,0)
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE TTA_HWB_ATTENDANCE_FEE IS 'Attendance Fee checking';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.ID IS 'ID';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.DEPT IS 'DEPT';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.BRAND_ENORCN IS 'Brand(EN/CN)';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.NUM IS '数量';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.FEE_TYPE IS 'Type';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.RATE_CARD IS 'Rate card';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.FEE_GROUP IS 'Group';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.CATEGORY IS 'Category';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.CONTENT IS '活动内容';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.VENDOR_CODE IS '需采购确认供应商编号';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.VENDOR_NAME IS '需采购确认供应商名字';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.BRAND IS '品牌';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.AMOUNT IS '应收金额';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.CONFIRM_AMOUNT IS '采购确认收款金额';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.FG IS 'FG';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.DIFFERENT IS '差异';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.ACTIVE IS '采购行动';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.PROJECT_TYPE IS '项目类型（TTA/OnTop)';
COMMENT ON COLUMN TTA_HWB_ATTENDANCE_FEE.REMARK IS '备注(如采购行动选择确认不收取或者折扣收取请在备注详细说明原因)';


ALTER TABLE TTA_HWB_ATTENDANCE_FEE ADD PRIMARY KEY (ID);
