create sequence SEQ_TTA_AWARD_POLIST  

increment by 1  

start with 1  

maxvalue 99999999  

cycle  

nocache;  

CREATE TABLE TTA_AWARD_POLIST (
ID NUMBER  NOT NULL,
DEPT VARCHAR2(100),
AWARD_DESCRIPTION_EN VARCHAR2(100),
AWARD_DESCRIPTION_CN VARCHAR2(100),
DM_POP_CN VARCHAR2(100),
RATE_CARD_2017 VARCHAR2(50),
RATE_CARD_2018 VARCHAR2(50),
ACT_SUPPLIER_OI_2018 VARCHAR2(50),
OI_GAP VARCHAR2(50),
DM_PAGE VARCHAR2(50),
DM_RATE_CARD VARCHAR2(50),
SUGGESTED_OSD_LOCATION VARCHAR2(50),
BIDDING_OSD VARCHAR2(50),
BRAND_PRODUCT_NAME_CN VARCHAR2(100),
PR_AWARD VARCHAR2(250),

TIMES_VERSION VARCHAR2(50),
STATUS VARCHAR2(50),

CREATION_DATE DATE DEFAULT SYSDATE, 
CREATED_BY NUMBER(*,0), 
LAST_UPDATED_BY NUMBER(*,0), 
LAST_UPDATE_DATE DATE DEFAULT SYSDATE, 
LAST_UPDATE_LOGIN NUMBER(*,0)
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE TTA_AWARD_POLIST IS ' AWARD_POLIST';
COMMENT ON COLUMN TTA_AWARD_POLIST.ID IS 'ID';
COMMENT ON COLUMN TTA_AWARD_POLIST.ACT_SUPPLIER_OI_2018 IS '2018 ACT Supplier OI (000)';
COMMENT ON COLUMN TTA_AWARD_POLIST.RATE_CARD_2018 IS '2018 Rate Card (000)';
COMMENT ON COLUMN TTA_AWARD_POLIST.RATE_CARD_2017 IS '2017 Rate Card (000)';
COMMENT ON COLUMN TTA_AWARD_POLIST.DM_POP_CN IS 'Award Description on DM & POP£®CN£©Final';
COMMENT ON COLUMN TTA_AWARD_POLIST.BRAND_PRODUCT_NAME_CN IS 'Brand/ Product Name£®Chinese£©';
COMMENT ON COLUMN TTA_AWARD_POLIST.PR_AWARD IS 'PRΩ±œÓ£®ºŒ»À‘”÷æ£©';


ALTER TABLE TTA_AWARD_POLIST ADD PRIMARY KEY (ID);
