server:
  port: 8761
spring:
  application:
    name : 1003_saaf-zipkin-center
  zipkin:
    enabled: false
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://139.159.227.87:3313/saafbase5?zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&useSSL=true
    username: app
    password: Sieapp123@
    initialize: true
    continueOnError: true
  sleuth:
    enabled: false
  storage:
    type: mysql
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
eureka:
  instance:
    appname: 1003_saaf-zipkin-center
    hostname: localhost
    prefer-ip-address: true
    port: 8760
  client:
    serviceUrl:
      #defaultZone: http://admin:admin@localhost:8760/eureka/
      defaultZone: http://admin:admin@${eureka.instance.hostname}:${eureka.instance.port}/eureka/
