server:
  port: 2000
  tomcat:
    max-threads: 2000
    accept-count: 200
    max-connections: 2000
    max-http-post-size: -1
    uri-encoding: UTF-8 #配置字符集
  #context-path: /ttaServer

management:
  security:
    enabled : false

spring:
  application:
    name: 2000-saaf-tta-server
#  zipkin:
#    base-url: http://admin:admin@${eureka.instance.hostname}:8761
#  mail:
#    host: smtp.exmail.qq.com
#    username: xxxx@chinasie.com
#    password: xxxx
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
  http:
  #文件上传配置
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
    encoding:
      enabled: true
      charset: UTF-8
      force: true

endpoints:
  shutdown:
    enabled: true
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:${eureka.instance.port}/eureka/ #多个注册中心用逗号分隔
  instance:
    #hostname: 139.159.227.77
    hostname: 127.0.0.1
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #prefer-ip-address: true
    port: 8760

#阿里oss 配置
oss:
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAIR3y4zOJRynX7
  accessKeySecret: jhxrupOChDUWc6kVvSWff9Y1Z0oDhp
  bucketName: saaf
  accessProtocol: http://

#fastdfs配置
fastdfs:
  connect_timeout_in_seconds: 2
  network_timeout_in_seconds: 30
  charset: utf-8
  http_anti_steal_token: false
  http_secret_key: FastDFS1234567890
  http_tracker_http_port: 80
  #http_tracker_http_port: 8080
  tracker_servers: #TrackerList参数,支持多个
    - 10.82.24.117:22122   #TTA System uat
    #- 10.82.31.213:22122   #TTA Prod
#    - 139.159.229.33:22122
#     - 10.195.36.168:22122
#     - 10.195.36.169:22122
    #- 120.79.71.137:22122 #hmb的阿里云服务器
  thumb_image: #缩略图生成参数
    width: 150
    height: 150
  access: #访问地址
    address: 10.82.24.117 #TTA System uat
    #address: 10.82.31.213 #TTA Prod
    #address: 120.79.71.137 #hmb的阿里云服务器
#   address: 10.195.36.168
    http_type: http://
    http_port: 8888
    #http_port: 80
#   http_port: 8081